Testing
Aydar710/Edamam pull request #8
Opened 2019-03-13 11:53 UTC by Aydar710

2019-03-13 14:35 UTC, kehtolaulu commented
![image](https://user-images.githubusercontent.com/36210323/54287272-63aa9980-45b6-11e9-9051-5455d63dd74f.png)

2019-03-14 04:32 UTC, kehtolaulu commented
![image](https://user-images.githubusercontent.com/36210323/54331492-4e238700-462b-11e9-955e-954f3deba474.png)

2019-03-14 07:25 UTC, nailshaykhraziev requested changes

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/presenters/DetailsFragmentPresenter.kt
> +open class DetailsFragmentPresenter(private val repository: RecipeRepository)
why?
вы ж подключили inline mockito который уже умеет с final классами работать

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/presenters/RecipeListFragmentPresenter.kt
> +open class RecipeListFragmentPresenter(private val repository: RecipeRepository)
- open

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/presenters/RecipeListFragmentPresenter.kt
> +//                                mList.addAll(list)
clear code

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/presenters/RecommendationFragmentPresenter.kt
> +open class RecommendationFragmentPresenter(
-

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/presenters/RecommendationFragmentPresenter.kt
> +    open fun getRandomRecipeIdFromList(): String {
- open

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/repositories/RecipeRepository.kt
> +open class RecipeRepository( val api: EdamamApi) {
- open

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/repositories/RecipeRepositoryDb.kt
> +open class RecipeRepositoryDb(context: Context) {
-open

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/main/java/com/m/edamam/ui/DetailsFragment.kt
> +    override fun handleError(error: Throwable) {
=
и snackbar

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/test/java/com/m/edamam/presenters/DetailsFragmentPresenterTest.kt
> +    private var repository: RecipeRepository = RecipeRepository(Retrofit.instance.getEdamamService())
@Mock
    private lateinit var repository: RecipeRepository

не нужно создавать настоязий объект. Тесты проходят на изоляции. Мы с каждого слоя всего мокаем и на максимальной изоляции тестим

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/test/java/com/m/edamam/presenters/DetailsFragmentPresenterTest.kt
> +}
add empty line

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/test/java/com/m/edamam/presenters/RecipeListFragmentPresenterTest.kt
> +}
add line

2019-03-14 07:25 UTC, nailshaykhraziev commented on app/src/test/java/com/m/edamam/presenters/RecommendationFragmentPresenterTest.kt
> +}
line

2019-03-14 11:58 UTC, kehtolaulu commented on app/src/main/java/com/m/edamam/ui/DetailsFragment.kt
> +    override fun handleError(error: Throwable) {
что?

2019-03-14 20:36 UTC, NailShaykhrazievItis approved these changes

2019-03-14 20:36 UTC, NailShaykhrazievItis commented on app/src/main/java/com/m/edamam/ui/DetailsFragment.kt
> +    override fun handleError(error: Throwable) {
> что?

override fun handleError(error: Throwable) = Snackbar(.....).show()

2019-03-15 16:30 UTC, merged